name: rebase

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: >
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, '/rebase') && (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3.0.1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Rebase â¤´ï¸
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
